using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace Relatorios.mod_desenvolvimento.relatorios
{
    public static class Cartelinha
    {

        private static string QuebraLinha(string value)
        {
            StringBuilder quebraLinha = new StringBuilder();
            quebraLinha.Append(value);
            int primeiroEspaco = quebraLinha.ToString().IndexOf(' ');
            if (primeiroEspaco > 3)
            {
                quebraLinha.Remove(primeiroEspaco, 1);
                quebraLinha.Insert(primeiroEspaco, "<br />");
            }
            return quebraLinha.ToString();
        }

        public static string MontarCartelinha(DESENV_PEDIDO_QTDE desenvPedidoQtde)
        {
            var desenvController = new DesenvolvimentoController();
            var sb = new StringBuilder();

            DESENV_PEDIDO pedido = null;
            if (desenvPedidoQtde.DESENV_PEDIDO1 != null)
                pedido = desenvPedidoQtde.DESENV_PEDIDO1;
            else
                pedido = desenvController.ObterPedido(desenvPedidoQtde.DESENV_PEDIDO);

            var fornecedor = "";
            if (desenvPedidoQtde.DESENV_PEDIDO_SUB1 != null && desenvPedidoQtde.DESENV_PEDIDO_SUB1.FORNECEDOR != null && desenvPedidoQtde.DESENV_PEDIDO_SUB1.FORNECEDOR != "")
                fornecedor = desenvPedidoQtde.DESENV_PEDIDO_SUB1.FORNECEDOR;
            else
                fornecedor = pedido.FORNECEDOR.Trim();

            var comp = new List<MATERIAL_COMPOSICAO>();
            var materiais = desenvController.ObterMaterial(pedido.GRUPO, pedido.SUBGRUPO);
            foreach (var m in materiais)
            {
                var matCor = desenvController.ObterMaterialCor(m.MATERIAL, pedido.COR, pedido.COR_FORNECEDOR);
                if (matCor != null)
                {
                    comp = desenvController.ObterMaterialComposicao(m.MATERIAL);
                    if (comp != null && comp.Count() > 0)
                    {
                        break;
                    }
                }
            }

            sb.AppendLine("");

            sb.AppendLine("<!DOCTYPE HTML PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>");
            sb.AppendLine("<html>");
            sb.AppendLine("<head>");
            sb.AppendLine("    <title>CARTELINHA</title>");
            sb.AppendLine("    <meta charset='UTF-8' />");
            sb.AppendLine("    <style type='text/css'>");
            sb.AppendLine("        .breakafter");
            sb.AppendLine("        {");
            sb.AppendLine("            page-break-after: always;");
            sb.AppendLine("        }");
            sb.AppendLine("        .breakbefore");
            sb.AppendLine("        {");
            sb.AppendLine("            page-break-before: always;");
            sb.AppendLine("        }");
            sb.AppendLine("    </style>");
            sb.AppendLine("</head>");
            sb.AppendLine("<body onload='window.print();'>");
            sb.AppendLine("    <br />");
            sb.AppendLine("    <div id='divDetalheTipo' align='center'>");
            sb.AppendLine("        <br />");
            sb.AppendLine("        <table border='0' cellpadding='0' cellspacing='0' width='689' style='width: 517pt;");
            sb.AppendLine("            padding: 0px; color: black; font-size: 9.0pt; font-weight: 700; font-family: Arial, sans-serif;");
            sb.AppendLine("            background: white; white-space: nowrap;'>");
            sb.AppendLine("            <tr>");
            sb.AppendLine("                <td colspan='2' style='line-height: 16px;'>");
            sb.AppendLine("                    <table border='0' cellpadding='0' cellspacing='0' width='689' style='border-collapse: collapse;");
            sb.AppendLine("                        width: 517pt'>");
            sb.AppendLine("                        <tr style='border-right: 1px solid #000; border-top: 2px solid #000;'>");
            sb.AppendLine("                            <td colspan='3' style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                Fornecedor");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td colspan='2' style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Nota Fiscal");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-right: 1px solid #000;'>");
            sb.AppendLine("                            <td colspan='3' style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                &nbsp;" + fornecedor);
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td colspan='2' style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                &nbsp;" + desenvPedidoQtde.NOTA_FISCAL);
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-right: 1px solid #000; border-top: 2px solid #000;'>");
            sb.AppendLine("                            <td colspan='3' style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                Tecido");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td colspan='2' style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Total Nota");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-right: 1px solid #000;'>");
            sb.AppendLine("                            <td colspan='3' style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                &nbsp;" + pedido.GRUPO + " / " + pedido.SUBGRUPO + " - " + new ProducaoController().ObterCoresBasicas(pedido.COR).DESC_COR);
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td colspan='2' style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                &nbsp;" + ((desenvPedidoQtde.VALOR_NOTA != null) ? "R$ " + Convert.ToDecimal(desenvPedidoQtde.VALOR_NOTA).ToString("###,###,###,##0.00") : ""));
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-right: 1px solid #000; border-top: 2px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                1º Vencimento");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                2º Vencimento");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                3º Vencimento");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                4º Vencimento");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                5º Vencimento");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-right: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                &nbsp;" + ((desenvPedidoQtde.VENCIMENTO1 != null) ? Convert.ToDateTime(desenvPedidoQtde.VENCIMENTO1).ToString("dd/MM/yyyy") : ""));
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                &nbsp;" + ((desenvPedidoQtde.VENCIMENTO2 != null) ? Convert.ToDateTime(desenvPedidoQtde.VENCIMENTO2).ToString("dd/MM/yyyy") : ""));
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                &nbsp;" + ((desenvPedidoQtde.VENCIMENTO3 != null) ? Convert.ToDateTime(desenvPedidoQtde.VENCIMENTO3).ToString("dd/MM/yyyy") : ""));
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                &nbsp;" + ((desenvPedidoQtde.VENCIMENTO4 != null) ? Convert.ToDateTime(desenvPedidoQtde.VENCIMENTO4).ToString("dd/MM/yyyy") : ""));
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                &nbsp;" + ((desenvPedidoQtde.VENCIMENTO5 != null) ? Convert.ToDateTime(desenvPedidoQtde.VENCIMENTO5).ToString("dd/MM/yyyy") : ""));
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-right: 1px solid #000; border-top: 2px solid #000;'>");
            sb.AppendLine("                            <td colspan='5' style='border-right: 1px solid #000; border-left: 1px solid #000; '>");
            sb.AppendLine("                                Composição");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-right: 1px solid #000; border-bottom: 2px solid #000;'>");
            sb.AppendLine("                            <td colspan='5' style='border-right: 1px solid #000; border-left: 1px solid #000; '>");

            var composicaoPorLinha = "";
            foreach (var c in comp)
                composicaoPorLinha = composicaoPorLinha + (c.QTDE + "% " + c.DESCRICAO) + ", ";

            composicaoPorLinha = (composicaoPorLinha.Trim() + ",").Replace(",,", "");

            sb.AppendLine("                                &nbsp;" + composicaoPorLinha);

            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                    </table>");
            sb.AppendLine("                </td>");
            sb.AppendLine("            </tr>");
            sb.AppendLine("            <tr>");
            sb.AppendLine("                <td valign='top' style='width:180px; height:400px;'>");
            sb.AppendLine("                    <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: collapse;' width='100%'>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000; '>");
            sb.AppendLine("                            <td style='width: 130px; border-right: 1px solid #000; '>");
            sb.AppendLine("                                Data Entrada");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-bottom: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align:right;'>" + desenvPedidoQtde.DATA.ToString("dd/MM/yyyy") + "&nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000;'>");
            sb.AppendLine("                            <td valign='middle' style='text-align:center'>");
            sb.AppendLine("                                <img width='150' height='130' src='" + ((pedido.FOTO_TECIDO == null) ? "" : "..\\.." + (pedido.FOTO_TECIDO.Replace("~", "").Replace("/", "\\"))) + "' alt='' />");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Pedido");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000; line-height:10px;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align: right;'>" + pedido.NUMERO_PEDIDO.ToString() + " &nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; '>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Quantidade");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align: right;'>" + desenvPedidoQtde.QTDE.ToString("###,###,###,##0.00") + " " + pedido.UNIDADE_MEDIDA1.DESCRICAO + "s &nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000; '>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Preço");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000;'>");

            var preco = "";
            if (desenvPedidoQtde.DESENV_PEDIDO_SUB1 != null && desenvPedidoQtde.DESENV_PEDIDO_SUB1.VALOR != null)
                preco = Convert.ToDecimal(desenvPedidoQtde.DESENV_PEDIDO_SUB1.VALOR).ToString("###,###,###,##0.00");
            else
                preco = pedido.VALOR.ToString("###,###,###,##0.00");

            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align: right;'>R$ " + preco + " &nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000; '>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Produto Fornecedor");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align: right;'>" + desenvPedidoQtde.PRODUTO_FORNECEDOR + " &nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Cor Fornecedor");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000; line-height:18px;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align: right;'>" + ((pedido.COR_FORNECEDOR.Trim().Length > 15) ? QuebraLinha(pedido.COR_FORNECEDOR.Trim()) : pedido.COR_FORNECEDOR.Trim()) + " &nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000; '>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Largura");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align: right;'>" + ((desenvPedidoQtde.LARGURA != null) ? Convert.ToDecimal(desenvPedidoQtde.LARGURA).ToString("###,###,###,##0.00") : "") + " &nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Volume");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000; line-height:10px;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align: right;'>" + desenvPedidoQtde.VOLUME + " &nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height: 30px; border-left: 1px solid #000; border-right: 1px solid #000;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000;'>");
            sb.AppendLine("                                Rendimento (1 Metro em KGs)");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000; line-height:10px;'>");
            sb.AppendLine("                            <td style='border-right: 1px solid #000; text-align: right;'>" + ((desenvPedidoQtde.RENDIMENTO_MT != null) ? Convert.ToDecimal(desenvPedidoQtde.RENDIMENTO_MT).ToString("###,###,###,##0.000") : "") + " &nbsp;</td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr>");
            sb.AppendLine("                            <td style='line-height: 236px; border-left: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                    </table>");
            sb.AppendLine("                </td>");
            sb.AppendLine("                <td valign='top' style='text-align:left;'>");
            sb.AppendLine("                    <table border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse; width:100%'>");
            sb.AppendLine("                        <tr style='line-height:43px; text-align:center;'>");
            sb.AppendLine("                            <td>");
            sb.AppendLine("                                Data");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td>");
            sb.AppendLine("                                HB");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td>");
            sb.AppendLine("                                Produto");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='width:45px;'>");
            sb.AppendLine("                                Peças");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='width:55px;'>");
            sb.AppendLine("                                G. Folha");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='width:55px;'>");
            sb.AppendLine("                                Retalhos");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='width:60px;'>");
            sb.AppendLine("                                Total");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='width:60px;'>");
            sb.AppendLine("                                Estoque");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height:40px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height:40px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("");
            sb.AppendLine("                        <tr style='line-height:41px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("");
            sb.AppendLine("                        <tr style='line-height:41px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("");
            sb.AppendLine("                        <tr style='line-height:41px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("");
            sb.AppendLine("                        <tr style='line-height:41px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("");
            sb.AppendLine("                        <tr style='line-height:41px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("");
            sb.AppendLine("                        <tr style='line-height:41px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("");
            sb.AppendLine("                        <tr style='line-height:41px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("");
            sb.AppendLine("                        <tr style='line-height:42px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height:42px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height:42px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height:42px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                        <tr style='line-height:42px;'>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center; width:40px;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                            <td style='text-align:center;'>");
            sb.AppendLine("                                &nbsp;");
            sb.AppendLine("                            </td>");
            sb.AppendLine("                        </tr>");
            sb.AppendLine("                    </table>");
            sb.AppendLine("                </td>");
            sb.AppendLine("            </tr>");
            sb.AppendLine("");
            sb.AppendLine("        </table>");
            sb.AppendLine("    </div>");

            sb.AppendLine("</body>");
            sb.AppendLine("</html>");


            sb.AppendLine("");
            return sb.ToString();
        }

    }
}